### PR TITLE
Throw error message if najax not present.

### PR DESCRIPTION
**Pull request by kratiahuja**
This PR exposes per request meta data so that it can be used in the app. Related [PR in fastboot](https://github.com/ember-fastboot/fastboot/pull/91)

### CODE REVIEW

**Comment by arjansingh** [comment]
LGTM

**Comment by kratiahuja** [comment]
@rwjblue can you please review this as well? 😄

**Comment by kellyselden** [comment]
This looks like a duplicate of #245

**Comment by kratiahuja** [comment]
@kellyselden i rebased and squashed. Now it is not a duplicate but dependent on this [PR](https://github.com/ember-fastboot/fastboot/pull/92)

**Comment by kellyselden** [comment]
@kratiahuja Awesome.

**Pull request merged**
