### PR TITLE
Remove deprecated features for ember-cli-fastboot v3 release

### PR DESCRIPTION
**Pull request by xg-wang**
* `@service('fastboot')`
  * `cookies` -> `this.fastboot.request.cookies`
  * `headers` -> `this.fastboot.request.headers`
  * `host` -> `this.fastboot.request.host`
* `ember-addon.fastBootDependencies` -> `ember-addon.fastbootDependencies` (the lowercased 'b')
* `app/initializers|instance-initialzers/fastboot` -> `fastboot/initializers|instance-initializers/`

### CODE REVIEW

**Review by kiwiupover — CHANGES_REQUESTED** [review]
@xg-wang `test-packages/example-addon` should not be a submodule. I think it has a `.git` folder that needs to be deleted.

**Comment by xg-wang** [comment]
@kiwiupover yea, turns out if I rm -rf .git after adding it, it is still being tracked as submodule 🤦🏼

**Comment by kiwiupover** [comment]
@xg-wang this is better

**Review by kiwiupover — APPROVED** [review]

**Comment by kiwiupover** [comment]
@xg-wang Thanks.

**Pull request merged**
