### PR TITLE
Ensure `treeForFastBoot` is called for arbitrarily nested addons.

### PR DESCRIPTION
**Pull request by rwjblue**
Previously, we only called `treeForFastBoot` on the projects direct dependencies.

* updates to call `treeForFastBoot` at each layer (just like `treeFor` does)
* Ensures that we do not double process the raw addons `fastboot` folder **and**
  the result of `treeForFastBoot`.

Fixes https://github.com/ember-fastboot/ember-cli-fastboot/issues/420
Fixes https://github.com/ember-fastboot/ember-cli-fastboot/issues/421

### CODE REVIEW

**Comment by kratiahuja** [comment]
Thank you @rwjblue

**Comment by simonihmig** [comment]
Just tested these changes with the addon combination mentioned in #421, works like a charm, and indeed fixes that problem! Thanks a lot!

**Comment by rwjblue** [comment]
Thanks for reviewing @kratiahuja, and @simonihmig for confirming in the original failure scenario!

I won't have time to release tonight, not sure if @kratiahuja / @stefanpenner / or others do...

**Comment by kratiahuja** [comment]
I'll release tonight!

**Comment by kratiahuja** [comment]
ember-cli-fastboot@1.0.0-rc.3 is released!

**Pull request merged**
