### PR TITLE
Make manifest in package.json respect outputPaths configuration in EmberApp

### LINKED ISSUE #538: Manifest does not respect outputPaths configuration in EmberApp
This seems to be a regression as was previsouly fixed in #163.

If you define your own output paths for your vendor/app js files, FastBoot does not generate the proper manifest.

if you have the following in your ember-cli-build.js:
```javascript
outputPaths: {
    app: {
        js: '/my-app-assets/my-app.js'
    },
    vendor: {
        js: '/my-app-assets/vendor.js',
        css: '/my-app-assets/css/vendor.css'
    }
}
```

The `package.json` would contain:
```
"manifest": {
    "appFiles": [
        "assets/my-app.js",
        "assets/my-app-fastboot-de9ebe5f790e0b91c3f97996ac97531d.js"
    ],
    "htmlFile": "index.html",
    "vendorFiles": [
        "assets/vendor-96b161d4f7c70d5e7d0642b8f662db84.js"
    ]
}
```

### PR DESCRIPTION
**Pull request by SergeAstapov**
fixes #538

### CODE REVIEW

**Comment by kratiahuja** [comment]
@SergeAstapov do you know where the regression happened?

**Comment by SergeAstapov** [comment]
@kratiahuja after trying to see what caused a regression seems that #165 (which fixed #163 I'm referenced) was concerned about file name defined in `outputPaths` that does not match with app name and not about path itself.

Looking into commits history it does not seem a regression to me anymore, I was mislead by #163 title.

Problem we faced is that if we want to have non-default `/dist/assets` folder name (let's say `/dist/my-app-assets`) defined in `outputPaths` - the dist would be broken (FastBoot manifest would have wrong file paths with `/dist/assets` prefix).

**Comment by rwjblue** [comment]
Haven't reviewed the changed tests, but the general implementation looks sound to me...

**Comment by SergeAstapov** [comment]
@kratiahuja @rwjblue could you please merge PR if it seems good to you? I do not have permissions.
Thanks for feedback!

**Comment by kratiahuja** [comment]
Sorry I meant to merge this in.

**Pull request merged**
