### PR TITLE
Remove content between markers

### PR DESCRIPTION
**Pull request by cibernox**
Ready to merge

### CODE REVIEW

**Comment by cibernox** [comment]
Ok, I've now verified that this works with and without the `ember-glimmer-remove-application-template-wrapper` flag enabled, and in both cases it leaves the DOM clean of any old content or markers.

The only thing I'm not sure how to do is ensure that the `clear-double-boot` initializer runs after the shoebox information has been loaded. I actually think that this should not be enforced in this addon but on the addons expecting to use the shoebox instead. It seems more correct for those addons to be aware how fastboot works than fastboot being aware of all addons using a shoebox-like approach.

**Comment by cibernox** [comment]
@rwjblue @kratiahuja This is now ready 🎉

**Comment by kratiahuja** [comment]
@cibernox can please we make sure to add a test to make sure we don't regress this?

**Comment by cibernox** [comment]
I've added tests. I had to use imagination a bit to add a test for the initializer, but it's the best idea I came up with.

**Comment by kratiahuja** [comment]
Thank you @cibernox

**Comment by cibernox** [comment]
@kratiahuja Can I get a new release at some point this week?

**Comment by kratiahuja** [comment]
@cibernox Sure I will release tomorrow.

**Comment by cibernox** [comment]
@kratiahuja Did you forget about the release? 😉

**Comment by kratiahuja** [comment]
@cibernox Super sorry! Yes I forgot about the release. v1.1.3 is released.

**Comment by cibernox** [comment]
I've just verified that it works on an app using canary wth the flag
`ember-glimmer-remove-application-template-wrapper` enabled 🎉

2018-01-30 16:39 GMT+01:00 Krati Ahuja <notifications@github.com>:

**Comment by Sweet-Bob** [comment]
After 1.1.3 update i had a problem like this https://github.com/ember-fastboot/ember-cli-fastboot/issues/565 (Ember 2.18.0), but only with fastboot-app-server.
On 1.1.2 works fine.

**Comment by cibernox** [comment]
@Sweet-Bob Someone else reported it too. It's a problem in fastboot-app-server, it has to be upgraded to 1.1.3 too.

**Comment by Sweet-Bob** [comment]
@cibernox Should be reported to fastboot-app-server repo?

**Comment by cibernox** [comment]
PR done: https://github.com/ember-fastboot/fastboot-app-server/pull/73

**Comment by Sweet-Bob** [comment]
@cibernox Thank you!

**Pull request merged**
