### PR TITLE
[BUGFIX] fix build stability

### PR DESCRIPTION
**Pull request by stefanpenner**
This prevents fastboot from constantly writing its package.json if it has not changed.

- [x]  tests

### CODE REVIEW

**Comment by kratiahuja** [comment]
LGTM. I think there are existing tests around the package.json. What other tests did you have in mind?

**Comment by stefanpenner** [comment]
> I think there are existing tests around the package.json

Unit tests, the existing ones are too high level to add proper coverage (and also quite slow and brittle)

**Comment by stefanpenner** [comment]
@kratiahuja I have updated them. I would likely recommend we transition more and more of the tests to more targeted tests like this. Rather then the end to end tests we have now. I feel we have better confidence with the tests, easier to pin-point issues, easier to add additional scenarios etc, then the existing approach.

**Comment by simonihmig** [comment]
Tried this also, and can confirm this works perfectly.

For the record: this also fixes the issue that CSS hot reloading was not working correctly, the browser would always do a full reload even if just some CSS/Sass files changed.

**Comment by stefanpenner** [comment]
I'll release rc2 when I get to work

**Comment by stefanpenner** [comment]
released as v1.0.0-rc.2 🎉

**Pull request merged**
