### PR TITLE
Add back "Use relative protocol for redirects"

### PR DESCRIPTION
**Pull request by josemarluedke**
cc/ @kellyselden.

### CODE REVIEW

**Comment by kratiahuja** [comment]
@kellyselden @josemarluedke  can we hold this off until ember-cli-fastboot@1.0 ?

**Comment by kellyselden** [comment]
Fine by me

**Comment by kratiahuja** [comment]
@josemarluedke sorry you would need to merge conflicts again. could you merge conflicts, and then this is good to go.

**Comment by josemarluedke** [comment]
@kratiahuja rebased. This should be good to go now.

**Comment by kellyselden** [comment]
@josemarluedke Thanks again for resubmitting.

**Pull request merged**
