### PR TITLE
Expose body and method in fastboot service

### PR DESCRIPTION
**Pull request by cibernox**
The PR takes over #354 and finalizes the work started by @bcardarella 

The feature itself is very simple. It adds the properties `body` and `method` to the fastboot service so people can use them however they want.

This exposes the low level primitives needed for RFC https://github.com/emberjs/rfcs/pull/185

### CODE REVIEW

**Comment by bcardarella** [comment]
:party::beer:

**Comment by rwjblue** [comment]
Seems reasonable to me.  Basically, follows along with what we had decided in #354 and adds tests (which AFAICT was the only real blocker on #354).

**Comment by cibernox** [comment]
If there is any docs to add, please link me to the best place to document this and I'll update it after it's merged.

**Comment by kratiahuja** [comment]
@cibernox : http://ember-fastboot.com/docs/user-guide#request-host (Please add a section similar to this in ember-fastboot/fastboot-website)

**Comment by kratiahuja** [comment]
@cibernox merged this. I'll release once the fastboot-website PR is out to keep them in sync.

**Pull request merged**
