### PR TITLE
Update fastboot to 3.1.0

### PR DESCRIPTION
**Pull request by kiwiupover**
@kratiahuja @rwjblue Can we cut a release with fastboot@3.1.0

### CODE REVIEW

**Comment by kiwiupover** [comment]
Looks like a no with test failures

**Comment by kiwiupover** [comment]
This error is an upstream issue with glimmer-vm https://github.com/glimmerjs/glimmer-vm/issues/1141

`var nodeURL = _nodeModule.module.require('url');`

**Comment by rwjblue** [comment]
@kiwiupover - Have you had a chance to poke at the legacy test failures here? Any idea what is going on?

**Comment by kiwiupover** [comment]
@rwjblue this the upstream issue `var nodeURL = _nodeModule.module.require('url');`

**Comment by rwjblue** [comment]
> it is the upstream issue var nodeURL = _nodeModule.module.require('url');

Hmm, that is fixed though (I believe a few different folks have confirmed). What version is being used that has the issue?

**Comment by kiwiupover** [comment]
@rwjblue what version needs to be updated?

**Comment by rwjblue** [comment]
The latest `ember-source` `beta` channel tarball has the fixes, but if we are using `beta` tag from NPM that may still be affected (since `3.22.0-beta.2` has the bug, and `-beta.3` hasn't been published yet). I just don't know what version we are actually using here...

**Comment by rwjblue** [comment]
We identified that this is being defaulted to the NPM dist-tag for `beta` here:

https://github.com/tomdale/ember-cli-addon-tests/blob/d1068cf260284fa7e3d0145b8bb753a1778fb7d2/lib/utilities/pristine.js#L97

https://github.com/tomdale/ember-cli-addon-tests/blob/d1068cf260284fa7e3d0145b8bb753a1778fb7d2/lib/utilities/pristine.js#L289

**Comment by kiwiupover** [comment]
@rwjblue We have passing tests.

**Review by rwjblue — APPROVED** [review]

**Pull request merged**
