### PR TITLE
remove global flag.

### PR DESCRIPTION
**Pull request by stefanpenner**
Addons can check via:

this.project.addons.find(addon => addon.name === 'ember-cli-fastboot'):
this.project.findAddonByName('ember-cli-fastboot');

### CODE REVIEW

**Comment by kratiahuja** [comment]
This was introduced for a corner usecase for `ember-cli-head` to be backward compatible: https://github.com/ronco/ember-cli-head/blob/master/index.js#L13

**Comment by kratiahuja** [comment]
Though now that I think about it, this flag would not be needed if `treeForApp` in `ember-cli-head` is refactored.

**Comment by stefanpenner** [comment]
https://github.com/ronco/ember-cli-head/pull/30

**Comment by stefanpenner** [comment]
@kratiahuja ah, that would be even better. But if we need to check explicit things, (like capability) a version check may be more appropriate then a global flag.

But if it can be refactored away entirely, we should take that approach.

**Comment by kratiahuja** [comment]
Yeah I don't think we need the `if..else` really...

**Pull request merged**
