### PR TITLE
fastBootDependencies => fastbootDependencies

### LINKED ISSUE #277: unify app `fastbootDependencies` and addon `fastBootDependencies`
I got tripped up by the different casing. App uses `fastbootDependencies` [here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/2e913eb907d3a8aa2b64d87b2877704a365fa6bf/lib/broccoli/fastboot-config.js#L83) and addon uses `fastBootDependencies` [here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/2e913eb907d3a8aa2b64d87b2877704a365fa6bf/lib/broccoli/fastboot-config.js#L185).
We should decide the correct casing and unify them.

### PR DESCRIPTION
**Pull request by kellyselden**
Resolves #277.

Will need to be updated in the docs as well.

### CODE REVIEW

**Comment by danmcclain** [comment]
There are 18 matches for `fastBootDependencies`: https://github.com/search?q=fastBootDependencies&type=Code&utf8=✓

**Comment by kellyselden** [comment]
OK. I didn't know the pre 1.0 deprecation policy.

**Comment by kellyselden** [comment]
> There are 18 matches for fastBootDependencies

That is a case insensitive search. 5 uses including mine.

**Comment by danmcclain** [comment]
Valid, but I still think we should deprecate, since other addons are using it as well, plus it was publicly documented: https://github.com/ember-fastboot/fastboot-website/blob/9ee24367eca999e771164e3919c1c649c676e76a/markdown/docs/addon-author-guide.md#L230

**Comment by kellyselden** [comment]
deprecated. now prints:
```
DEPRECATION: ember-addon.fastBootDependencies has been replaced with ember-addon.fastbootDependencies [addon: ember-cli-moment-shim]
DEPRECATION: ember-addon.fastBootDependencies has been replaced with ember-addon.fastbootDependencies [addon: ember-data-fetch-support]
DEPRECATION: ember-addon.fastBootDependencies has been replaced with ember-addon.fastbootDependencies [addon: ember-network]
```

**Comment by rwjblue** [comment]
Awesome, thank you for that @kellyselden!

**Comment by danmcclain** [comment]
Thanks @kellyselden!

**Pull request merged**
